### ISSUE TITLE
Discord issue.

### ISSUE THREAD

**Issue by L0stMem** [Browncha023/EndInternetCensorship#1]
Discord qr code wont work and it says the website is unsecure and dangerous, please explain.

**Comment by Browncha023** [comment]
Sorry, a new update will release in a few days that adds support for discord and removes the proxy warnings. I will comment here and close this once it's released.

**Comment by Browncha023** [comment]
Ok, The update has released, with discord support. :)

**Comment by Browncha023** [comment]
While it is supported discord is no longer working. I will fix it hopefully soon.

**Comment by Browncha023** [comment]
Ok, it just wasn't on my wifi... nvrm. :|
