### ISSUE TITLE
Proxy Not Allowing Access/Not Working

### ISSUE THREAD

**Issue by mcbossowens** [Browncha023/EndInternetCensorship#15]
when i try to use the proxy it says Run The Repl To see output.  or proxy under matninse

**Comment by Browncha023** [comment]
Make sure you are on the subdomain that starts with unblock. This can still occur with the unblock version, but it is a lot less common. I'll leave this issue open until I fix it.

**Comment by mcbossowens** [comment]
i dont understand ?

**Comment by Browncha023** [comment]
The issue where the proxy says it's under maintenance only occurs if your on an old subdomain (e.g: proxy.endinternetcensorship.repl.co) if you go to the home page (home.endinternetcensorship.repl.co) and click "Proxy" in the nav {navigation} bar that will take you to the new subdomain (unblock.endinternetcensorship.repl.co).

**Comment by mcbossowens** [comment]
oh ok but one last thing do you think you can make something on the proxy
that can go straight to discord and it lets you use your mic and cam and
for it to not say connecting then disconnected over and over again ?

**Comment by Browncha023** [comment]
I can make a shortcut to discord on the site if enough people want it, though I can not add cam and mic support. I'm currently using womginx as the proxy for the site (which doesn't support cam or mic) so if you would like to have voice/cam support potentially added you can open an issue on that page: https://github.com/binary-person/womginx.

**Comment by Browncha023** [comment]
This has been fixed for a while on the main site. Closed - 2/17/22
