### ISSUE TITLE
Blocked For ASD

### ISSUE THREAD

**Issue by THEBEST1278** [Browncha023/EndInternetCensorship#21]
I tried opening up the games on this but it got blocked by the district so it doesn't work anymore. Is there a way you can fix this?

**Comment by Browncha023** [comment]
Don't worry, I'll unblock it soon. Man, I hate our school district. I'll keep this open until I'm done.

**Comment by THEBEST1278** [comment]
thx

**Comment by THEBEST1278** [comment]
They blocked the proxy too:(

**Comment by Browncha023** [comment]
Yeah, ik. Sorry, I'm working on fixing it. :)

**Comment by 0xyclean** [comment]
blocked in westada district 2

**Comment by thatonedude21** [comment]
f

**Comment by kingof985** [comment]
Works in bcps district dunno bout you

**Comment by Browncha023** [comment]
2/17/22 - Combining Issue With #5

**Comment by crystalmirror** [comment]
blocked in david douglas school district
