### ISSUE TITLE
Sites like geforce now are not working.

### ISSUE THREAD

**Issue by PitifulAttempt** [Browncha023/EndInternetCensorship#25]
need an alternative link

**Comment by PitifulAttempt** [comment]
Also, the other sites on the main page are blocked by securely, are there any other alternative links?

**Comment by Browncha023** [comment]
A 404 error means that page doesn't exist, and there are currently no alternative links as I'm currently working on the github port.

**Comment by PitifulAttempt** [comment]
alright
