### ISSUE TITLE
Embed Bug

### ISSUE THREAD

**Issue by BSD48org** [Browncha023/EndInternetCensorship#27]
![Screenshot 2022-02-10 214136](https://user-images.githubusercontent.com/97194742/153543004-60cf1dc6-e45b-4121-bc0f-a0ad6c942aa5.png)
![Screenshot 2022-02-10 214346](https://user-images.githubusercontent.com/97194742/153543199-5a91e894-1991-434c-941a-a85d362d983a.png)

It seems like a lot of HTML elements are blocked by the proxy. I hope there is a fix to this but I still thank you a lot for this

**Comment by Browncha023** [comment]
I'm sorry but there isn't one that I know of, I'm not a proxy developer so I can't do anything as major as this. I use womginx as the proxy: which I know does not support youtube ui. I might open up an issue for something like this, but it might not get fixed. Sorry. The most I can say is to try resetting your cache (ctrl+shift+r on chromebooks), though that likely won't help.
