### ISSUE TITLE
NOT AN ISSUE, just a question

### ISSUE THREAD

**Issue by ImPot8o** [Browncha023/EndInternetCensorship#3]
I dont think there is a way to leave a comment so im using this. you said this web site is easily movable, how do you do that? i just want to use the MineCraftJS, but my school blocks https://games.endinternetcensorship.repl.co/. any help would be great. do i just import this to repl? please help

**Comment by ImPot8o** [comment]
> I dont think there is a way to leave a comment so im using this. you said this web site is easily movable, how do you do that? i just want to use the MineCraftJS, but my school blocks https://games.endinternetcensorship.repl.co/. any help would be great. do i just import this to repl? please help

ok, if you copy the code in the index file, then paste it into a html project in repl, you can play it there. hope this helps anyone else

**Comment by Browncha023** [comment]
As you said I have set it up so that the code can just be copied, but there are a bunch of bugs if you just do that. I will add the code to this repository soon so it can just be forked. If you need just MinecraftJS the two files are in my repository: "MinecraftJS".

**Comment by Browncha023** [comment]
When I said easily moved I meant for my school district, when it gets blocked. Sorry for the inconvenience.

**Comment by ImPot8o** [comment]
ok, i didnt see code for the proxy, so i have no idea how to make that work (i tried copying the page source, kinda worked, but not at all) but thanks for this project its really cool

**Comment by Browncha023** [comment]
Yeah, the proxy is a little more complicated, it's running womginx so it's a little janky. I don't know if I'll make that code public or not, sorry. I'm trying a few solutions to make it open-source but like I said, it's complicated.
