### ISSUE TITLE
discord replit not working.

### ISSUE THREAD

**Issue by crystalmirror** [Browncha023/EndInternetCensorship#36]
hi, i've been using the endinternetcensorship proxy for a few days now, it's so useful! however, as of around 15 minutes ago, i discovered that discord fully loads, but does not display messages. instead, it has a red error at the bottom saying "Messages failed to load". could you please fix this? my school uses iBoss. screenshot attached. 
![image](https://user-images.githubusercontent.com/90491956/155632589-fff9cae7-8a8a-420a-8232-b0fc30cf54c6.png)

**Comment by Browncha023** [comment]
I'm sorry but I can't fix this, as it's an issue with the proxy I use (being womginx), you can try resetting your cache, or you can wait for the github version of my site to come out. The github port will contain the option to add in the latest version of womginx (hopefully) where discord bugs are currently being worked on.
