### ISSUE TITLE
Proxy Unavailable

### ISSUE THREAD

**Issue by PitifulAttempt** [Browncha023/EndInternetCensorship#37]
![image](https://user-images.githubusercontent.com/98474803/156042746-433f1b32-93c9-4265-8760-dfa1cebc49bd.png)

**Comment by Browncha023** [comment]
Could you specify which sub-domain your trying to access? (e.g: games.endinternetcensorship.repl.co)

**Comment by Trunkers** [comment]
Agreed, for me it is https://unblock.endinternetcensorship.repl.co/

**Comment by thatsfishy** [comment]
> Could you specify which sub-domain your trying to access? (e.g: games.endinternetcensorship.repl.co)

unblock.endinternetcensorship.repl.co

**Comment by Trunkers** [comment]
BTW, it works again for me.

**Comment by PitifulAttempt** [comment]
works now
