### ISSUE TITLE
carrd creating and editing uncompatible + formatting issues

### ISSUE THREAD

**Issue by crystalmirror** [Browncha023/EndInternetCensorship#42]
if you use the unblocker/proxy, the text on my [carrd](https://kayslay.carrd.co) does not format correctly (i.e. the bold and italics). also, editing carrds are not possible using the proxy, since chrome pulls up a phishing alert. both of these are not escapable.

**Comment by Browncha023** [comment]
The old replit demo is no longer supported, all issues with it are up in the air. You can see if either of these issues are solved when the github port releases. I don't have a set release date as I already made that mistake and I've been really busy with school.
