### ISSUE TITLE
endinternetcensorship.repl.co not working

### ISSUE THREAD

**Issue by Elemperor1** [Browncha023/EndInternetCensorship#48]
Whenever I try to open home.endinternetcensorship.repl.co, unblock.endinternetcensorship.repl.co, or games.endinternetcensorship.repl.co, it takes a long time to load, and then it gives me a screen that looks like this:
<img width="1440" alt="Screen Shot 2022-04-08 at 9 26 13 AM" src="https://user-images.githubusercontent.com/48484869/162445016-0d59dfa2-573a-4b4a-a781-4bf1a11f30ee.png">

I was just wondering if anybody else was having this issue, and if so, if you are planning on fixing it soon?

**Comment by username-pass** [comment]
Everything is fine for me. Try disconnecting and reconnecting from the internet, or running connectivity diagnostics, that usually works for me.

**Comment by Elemperor1** [comment]
Still doesn't work for me, even after I did all of that stuff @username-pass

**Comment by Browncha023** [comment]
What device are you using? Where are you using it? It's likely a block but if not, there could be a fix.

**Comment by Elemperor1** [comment]
I am using a apple mac book at school.

**Comment by Browncha023** [comment]
Ok, so that means it's blocked. By either a school program like LanSchool or a Wifi block. The solutions are to either change wifi, disable school programs/use a personal computer, or to wait for the Github EIC port.
