### ISSUE TITLE
site wont work?

### ISSUE THREAD

**Issue by Gooseuberalles** [Browncha023/EndInternetCensorship#50]
just me or is https://home.endinternetcensorship.repl.co/ not working for anyone else?
gives me the replit.com run the repl to see output
tf am i supposed to do lmao

**Comment by Browncha023** [comment]
I'm closing all issues as I am completely ending support for EIC, I've already phased out of supporting it for a while now. It has not received any updates in months and the github port will be left in an unfinished state. Thank you for using EIC!
