### ISSUE TITLE
BLOCKED

### ISSUE THREAD

**Issue by Defualted** [Browncha023/EndInternetCensorship#52]
Sorry to say, but it is blocked on Iboss Please fix that if you dont know what Iboss is its a thing that blocks websites… pretty obvious but please fix it.. the description that iboss says on the website.. it says web proxies.. fix it.. Please? 
![93C3A3EF-C700-4CBD-B624-D522506B0386](https://user-images.githubusercontent.com/94013534/165117739-4c986290-ab2b-4c6e-99b9-1c4d8f29dde6.jpeg)

**Comment by Browncha023** [comment]
I'm closing all issues as I am completely ending support for EIC, I've already phased out of supporting it for a while now. It has not received any updates in months and the github port will be left in an unfinished state. Thank you for using EIC!
