### ISSUE TITLE
Any update on the new update?

### ISSUE THREAD

**Issue by username-pass** [Browncha023/EndInternetCensorship#55]
Earlier you sid that you would make it so that anyone could copy this site so it never gets blocked on march 1st. I understand that school does take a lot of time, I just want to know if there is any update on the update?

**Comment by THEBEST1278** [comment]
So what you can do is fork this repository then make a REPLIT acc then just import the repository to repair then you have your own version of the website.you can change whatever you want even  add more games

**Comment by THEBEST1278** [comment]
Here’s an example

**Comment by THEBEST1278** [comment]
Mathisfun.thebest1278.repl.co

**Comment by username-pass** [comment]
Thank you, that really helped. I have one last question: Do you by any chance know how it does it's XOR? The codec says XOR, but I am not sure what they are XORing it with, I want to make a thing where it takes the URL and automatically inputs that to .

**Comment by username-pass** [comment]
Oh, I figured it out. :) thanks for your help!

**Comment by THEBEST1278** [comment]
Np

**Comment by MakoSharkL0L** [comment]
is there any new vpns

**Comment by THEBEST1278** [comment]
VPNs?

**Comment by Browncha023** [comment]
I'm closing all issues as I am completely ending support for EIC, I've already phased out of supporting it for a while now. It has not received any updates in months and the github port will be left in an unfinished state. Thank you for using EIC!
