### ISSUE TITLE
change the url

### ISSUE THREAD

**Issue by crystalmirror** [Browncha023/EndInternetCensorship#57]
the unblocker at my school looks for keywords in the urls, and most recently in the domains. as of current, it has blocked the proxy. 
![image](https://user-images.githubusercontent.com/90491956/167739369-e9a62ba7-115f-4f86-9b7e-8a78e83407c1.png)
i don't know if you can see that,,,
the "unblock" in "https://unblock.endinternetcensorship.repl.co" is blocking my usage of the site. please fix this asap. thanks.

**Comment by THEBEST1278** [comment]
Here use this games.innerturtle123.repl.co
Mathisfun.thebest1278.repl.co

**Comment by crystalmirror** [comment]
.co is blocked too unfortunately

**Comment by THEBEST1278** [comment]
Ohh that’s tough
Use these 
Thebest1278.netlify.app

**Comment by crystalmirror** [comment]
anything that isn't .com .net .org or .edu is blocked :(

**Comment by crystalmirror** [comment]
see 
![image](https://user-images.githubusercontent.com/90491956/167969354-a819499b-4a09-4f6f-87ab-b2fc80c793e4.png)

**Comment by Browncha023** [comment]
I'm closing all issues as I am completely ending support for EIC, I've already phased out of supporting it for a while now. It has not received any updates in months and the github port will be left in an unfinished state. Thank you for using EIC!
